# Generated by Django 5.2.1 on 2025-11-21 20:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abrir_Cerrar_CAJA', '0001_initial'),
        ('Config_PR', '0001_initial'),
        ('Control_STOCK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('total_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('DELETE_Comp', models.BooleanField(default=False)),
                ('estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_MetodoPago',
            fields=[
                ('id_comp_metpag', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_comp_metpag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Comp_MetPag', models.BooleanField(default=False)),
                ('metodo_pago_comp_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.metodos_pago')),
                ('compra_comp_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='Control_COMPRAS.compras')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compras',
            fields=[
                ('id_det_comp', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unidad_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_det_comp', models.PositiveIntegerField()),
                ('subtotal_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Det_Comp', models.BooleanField(default=False)),
                ('compra_dt_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Control_COMPRAS.compras')),
                ('producto_dt_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Control_STOCK.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('razon_social_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.CharField(max_length=20)),
                ('cuit_proveedor', models.CharField(max_length=100)),
                ('correo_proveedor', models.EmailField(max_length=100)),
                ('DELETE_Prov', models.BooleanField(default=False)),
                ('estado_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Control_COMPRAS.proveedores'),
        ),
        migrations.CreateModel(
            name='Proveedores_Productos',
            fields=[
                ('id_prov_x_prod', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario_prov_x_prod', models.IntegerField()),
                ('DELETE_Prov_X_Prod', models.BooleanField(default=False)),
                ('producto_prov_x_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_STOCK.productos')),
                ('proveedor_prov_x_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_COMPRAS.proveedores')),
            ],
        ),
    ]
