# Generated by Django 5.2.1 on 2025-10-27 11:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_COMPRAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
