# Generated by Django 5.2.1 on 2025-11-21 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=100)),
                ('DELETE_Barrio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('DELETE_Ciud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('DELETE_Provin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calles',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=100)),
                ('DELETE_Calle', models.BooleanField(default=False)),
                ('barrio_calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.barrios')),
            ],
        ),
        migrations.AddField(
            model_name='barrios',
            name='ciudad_barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.ciudades'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('DELETE_Cli', models.BooleanField(default=False)),
                ('user_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=100)),
                ('departamento_direccion', models.CharField(max_length=100)),
                ('referecia_direccion', models.CharField(max_length=100)),
                ('DELETE_Dir', models.BooleanField(default=False)),
                ('calle_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.calles')),
                ('usuario_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_empleado', models.CharField(max_length=50)),
                ('telefono_empleado', models.CharField(max_length=50)),
                ('fecha_alta_empleado', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja_empleado', models.DateTimeField(blank=True, null=True)),
                ('DELETE_Emple', models.BooleanField(default=False)),
                ('user_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('JEFE', 'Jefe'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='provincia_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.provincias'),
        ),
        migrations.CreateModel(
            name='Telefonos_Usuarios',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('DELETE_Tel_U', models.BooleanField(default=False)),
                ('usuario_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
