# Generated by Django 5.2.1 on 2025-10-21 20:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abrir_Cerrar_CAJA', '0001_initial'),
        ('Config_PR', '0001_initial'),
        ('Control_STOCK', '0001_initial'),
        ('Fidelizar_CLIENTES', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=200)),
                ('DELETE_Met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('observaciones_venta', models.CharField(max_length=200)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vuelto_entregado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('DELETE_Vent', models.BooleanField(default=False)),
                ('caja_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.cajas')),
                ('cliente_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.clientes')),
                ('empleado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.empleados')),
                ('estado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
                ('promo_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fidelizar_CLIENTES.promos_clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Ventas',
            fields=[
                ('id_det_vent', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario_det_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_det_vent', models.IntegerField()),
                ('subtotal_det_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_det_vent', models.CharField(max_length=200)),
                ('DELETE_Det_Vent', models.BooleanField(default=False)),
                ('producto_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_STOCK.productos')),
                ('venta_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Control_VENTAS.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELETE_Vent_MetPag', models.BooleanField(default=False)),
                ('metodopago_vent_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_VENTAS.metodos_pago')),
                ('venta_vent_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_VENTAS.ventas')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metodopago_vent_metpag', 'venta_vent_metpag'), name='unique_venta_metodopago_combinacion')],
            },
        ),
    ]
