# Generated by Django 5.2.1 on 2025-11-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abrir_Cerrar_CAJA', '0002_initial'),
        ('Control_VENTAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta_metodopago',
            name='metodopago_vent_metpag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.metodos_pago'),
        ),
        migrations.DeleteModel(
            name='Metodos_Pago',
        ),
    ]
