# Generated by Django 5.2.1 on 2025-10-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Config_PR', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias_Productos',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=150)),
                ('DELETE_CateP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro_producto', models.DateTimeField(auto_now_add=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_unitario_compra_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_unitario_venta_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_vencimiento_producto', models.DateTimeField(blank=True, null=True)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('barcode', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('DELETE_Prod', models.BooleanField(default=False)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_STOCK.categorias_productos')),
                ('estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_actual_stock', models.IntegerField()),
                ('lote_stock', models.IntegerField()),
                ('observaciones_stock', models.CharField(max_length=300)),
                ('DELETE_Stock', models.BooleanField(default=False)),
                ('producto_en_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_STOCK.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Stock',
            fields=[
                ('id_historial_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_hstock', models.CharField(max_length=100)),
                ('fecha_movimiento_hstock', models.DateTimeField(auto_now_add=True)),
                ('stock_anterior_hstock', models.IntegerField()),
                ('stock_nuevo_hstock', models.IntegerField()),
                ('observaciones_hstock', models.CharField(max_length=300)),
                ('DELETE_Hstock', models.BooleanField(default=False)),
                ('empleado_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.empleados')),
                ('tipo_movimiento_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.tipos_movimientos')),
                ('stock_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_STOCK.stocks')),
            ],
        ),
    ]
