# Generated by Django 5.2.1 on 2025-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_STOCK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen_producto',
            field=models.ImageField(blank=True, help_text='Foto del producto', null=True, upload_to='productos/%Y/%m/'),
        ),
    ]
