# Generated by Django 5.2.1 on 2025-11-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_STOCK', '0002_productos_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/'),
        ),
    ]
