# Generated by Django 5.2.1 on 2025-10-28 23:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Config_PR', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=200)),
                ('DELETE_Met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_Fondo',
            fields=[
                ('id_mov_fp', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_mov_fp', models.DateTimeField(auto_now_add=True)),
                ('monto_mov_fp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo_mov_fp', models.CharField(blank=True, max_length=200)),
                ('DELETE_Mov_Fp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=50)),
                ('DELETE_Event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('total_gastos_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_apertura_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cierre_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_teorico_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones_caja', models.CharField(max_length=200)),
                ('DELETE_Caja', models.BooleanField(default=False)),
                ('estado_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Fondo_Pagos',
            fields=[
                ('id_fondo_fp', models.BigAutoField(primary_key=True, serialize=False)),
                ('saldo_fp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('DELETE_fp', models.BooleanField(default=True)),
                ('fecha_fp', models.DateTimeField(auto_now_add=True)),
                ('estado_fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Caja',
            fields=[
                ('id_historial_caja', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_movida_hcaja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino_movimiento', models.CharField(blank=True, choices=[('DEPOSITAR_OTROS', 'Depositar/Otros'), ('PARA_PAGOS_FONDO', 'Para pagos (Fondo)'), ('OTRO', 'Otro')], max_length=50, null=True)),
                ('fecha_movimiento_hcaja', models.DateTimeField(auto_now_add=True)),
                ('saldo_anterior_hcaja', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nuevo_saldo_hcaja', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descripcion_hcaja', models.CharField(max_length=300)),
                ('DELETE_Hcaja', models.BooleanField(default=False)),
                ('caja_hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.cajas')),
                ('empleado_hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Movimientos_Financieros',
            fields=[
                ('id_historial_mov_fin', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_mov_fin', models.DateTimeField(auto_now_add=True)),
                ('monto_mov_fin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Hist_Mov_Fin', models.BooleanField(default=False)),
                ('Historial_Caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.historial_caja')),
                ('caja_mov_fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.cajas')),
            ],
        ),
    ]
