# Generated by Django 5.2.1 on 2025-10-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abrir_Cerrar_CAJA', '0001_initial'),
        ('Config_PR', '0001_initial'),
        ('Control_COMPRAS', '0001_initial'),
        ('Control_VENTAS', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='compra_mov_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control_COMPRAS.compras'),
        ),
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='venta_mov_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control_VENTAS.ventas'),
        ),
        migrations.AddField(
            model_name='movimiento_fondo',
            name='empleado_mov_fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion.empleados'),
        ),
        migrations.AddField(
            model_name='movimiento_fondo',
            name='fondo_mov_fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Abrir_Cerrar_CAJA.fondo_pagos'),
        ),
        migrations.AddField(
            model_name='movimiento_fondo',
            name='tipo_mov_fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.tipos_movimientos'),
        ),
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='Movimiento_Fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.movimiento_fondo'),
        ),
        migrations.AddField(
            model_name='historial_caja',
            name='tipo_event_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abrir_Cerrar_CAJA.tipo_evento'),
        ),
    ]
