# Generated by Django 5.2.1 on 2025-10-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('DELETE_Est', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Estados',
            fields=[
                ('id_tipo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_estado', models.CharField(max_length=50)),
                ('DELETE_TE', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Movimientos',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=100)),
                ('is_transfer', models.BooleanField(default=False)),
                ('DELETE_TM', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alerta', models.CharField(max_length=100)),
                ('mensaje_alerta', models.CharField(max_length=500)),
                ('DELETE_Alerta', models.BooleanField(default=False)),
                ('estado_alerta', models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.AddField(
            model_name='estados',
            name='tipo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.tipos_estados'),
        ),
    ]
