# Generated by Django 5.2.1 on 2025-11-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config_PR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Puerto Real', max_length=100)),
                ('direccion', models.CharField(blank=True, help_text='Dirección física de la tienda.', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto público.', max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, help_text='Sitio web de la tienda.', null=True)),
            ],
            options={
                'verbose_name': 'Configuración de la Tienda',
                'verbose_name_plural': 'Configuración de la Tienda',
            },
        ),
    ]
