# Generated by Django 5.2.1 on 2025-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config_PR', '0002_configuraciontienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_por_compra', models.DecimalField(decimal_places=2, default=1, help_text='Factor de conversión de dinero a puntos. E.g., 1 punto por cada $100.', max_digits=10)),
                ('valor_punto', models.DecimalField(decimal_places=2, default=1, help_text='Valor de 1 punto en dinero para canje. E.g., 1 punto = $1.', max_digits=10)),
                ('puntos_por_referido', models.IntegerField(default=100, help_text='Puntos otorgados por cada cliente referido.')),
            ],
            options={
                'verbose_name': 'Configuración de Puntos',
                'verbose_name_plural': 'Configuración de Puntos',
            },
        ),
    ]
