# Generated by Django 5.2.1 on 2025-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config_PR', '0003_configuracionpuntos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='tipos_estados',
            name='nombre_tipo_estado',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='estados',
            unique_together={('nombre_estado', 'tipo_estado')},
        ),
    ]
