# Generated by Django 5.2.1 on 2025-09-01 18:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=100)),
                ('DELETE_Barrio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_Productos',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=150)),
                ('DELETE_CateP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('DELETE_Ciud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Descuento',
            fields=[
                ('id_cupon_desc', models.BigAutoField(primary_key=True, serialize=False)),
                ('descuento_porcentaje_cupon_desc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_monto_cupon_desc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_requeridos_cupon_desc', models.IntegerField()),
                ('nombre_cupon_desc', models.CharField(max_length=100)),
                ('descripcion_cupon_desc', models.CharField(max_length=300)),
                ('fecha_inicio_cupon_desc', models.DateField()),
                ('fecha_vencimiento_cupon_desc', models.DateField()),
                ('DELETE_Cupon_Desc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('DELETE_Est', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=200)),
                ('DELETE_Met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('DELETE_Provin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=50)),
                ('DELETE_Event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Estados',
            fields=[
                ('id_tipo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_estado', models.CharField(max_length=50)),
                ('DELETE_TE', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Movimientos',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=50)),
                ('DELETE_TM', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calles',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=100)),
                ('DELETE_Calle', models.BooleanField(default=False)),
                ('barrio_calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.barrios')),
            ],
        ),
        migrations.AddField(
            model_name='barrios',
            name='ciudad_barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ciudades'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('DELETE_Cli', models.BooleanField(default=False)),
                ('user_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Clientes',
            fields=[
                ('id_cupon_cli', models.BigAutoField(primary_key=True, serialize=False)),
                ('DELETE_Cupon_Clie', models.BooleanField(default=False)),
                ('cliente_cupon_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
                ('cupon_descuento_cupon_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cupones_descuento')),
                ('estado_cupon_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=100)),
                ('departamento_direccion', models.CharField(max_length=100)),
                ('referecia_direccion', models.CharField(max_length=100)),
                ('DELETE_Dir', models.BooleanField(default=False)),
                ('calle_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.calles')),
                ('usuario_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_empleado', models.CharField(max_length=50)),
                ('telefono_empleado', models.CharField(max_length=50)),
                ('fecha_alta_empleado', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja_empleado', models.DateTimeField(blank=True, null=True)),
                ('DELETE_Emple', models.BooleanField(default=False)),
                ('user_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Comp', models.BooleanField(default=False)),
                ('estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('total_gastos_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_apertura_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cierre_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_teorico_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones_caja', models.CharField(max_length=200)),
                ('DELETE_Caja', models.BooleanField(default=False)),
                ('estado_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alerta', models.CharField(max_length=100)),
                ('mensaje_alerta', models.CharField(max_length=500)),
                ('DELETE_Alerta', models.BooleanField(default=False)),
                ('estado_alerta', models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Fondo_Pagos',
            fields=[
                ('id_fondo_fp', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_fp', models.CharField(default='Fondo Pagos', max_length=100)),
                ('saldo_fp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('DELETE_fp', models.BooleanField(default=True)),
                ('fecha_fp', models.DateTimeField(auto_now_add=True)),
                ('estado_fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_Fondo',
            fields=[
                ('id_mov_fp', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_mov_fp', models.DateTimeField(auto_now_add=True)),
                ('tipo_mov_fp', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('monto_mov_fp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo_mov_fp', models.CharField(blank=True, max_length=200)),
                ('empleado_mov_fp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HOME.empleados')),
                ('fondo_mov_fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='HOME.fondo_pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro_producto', models.DateTimeField(auto_now_add=True)),
                ('descripcion_producto', models.CharField(max_length=500)),
                ('marca_producto', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_unitario_compra_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_unitario_venta_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DELETE_Prod', models.BooleanField(default=False)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.categorias_productos')),
                ('estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compras',
            fields=[
                ('id_det_comp', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unidad_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_det_comp', models.PositiveIntegerField()),
                ('subtotal_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Det_Comp', models.BooleanField(default=False)),
                ('compra_dt_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='HOME.compras')),
                ('producto_dt_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('razon_social_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.CharField(max_length=20)),
                ('cuit_proveedor', models.CharField(max_length=100)),
                ('correo_proveedor', models.EmailField(max_length=100)),
                ('DELETE_Prov', models.BooleanField(default=False)),
                ('estado_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HOME.proveedores'),
        ),
        migrations.CreateModel(
            name='Proveedores_Productos',
            fields=[
                ('id_prov_x_prod', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario_prov_x_prod', models.IntegerField()),
                ('DELETE_Prov_X_Prod', models.BooleanField(default=False)),
                ('producto_prov_x_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
                ('proveedor_prov_x_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.proveedores')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='provincia_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.provincias'),
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_actual_stock', models.IntegerField()),
                ('lote_stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('observaciones_stock', models.CharField(max_length=300)),
                ('DELETE_Stock', models.BooleanField(default=False)),
                ('producto_en_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Caja',
            fields=[
                ('id_historial_caja', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_movida_hcaja', models.CharField(max_length=100)),
                ('destino_movimiento', models.CharField(blank=True, choices=[('DEPOSITAR_OTROS', 'Depositar/Otros'), ('PARA_PAGOS_FONDO', 'Para pagos (Fondo)'), ('OTRO', 'Otro')], max_length=50, null=True)),
                ('fecha_movimiento_hcaja', models.DateTimeField(auto_now_add=True)),
                ('saldo_anterior_hcaja', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nuevo_saldo_hcaja', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descripcion_hcaja', models.CharField(max_length=300)),
                ('DELETE_Hcaja', models.BooleanField(default=False)),
                ('caja_hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cajas')),
                ('empleado_hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('tipo_event_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.tipo_evento')),
            ],
        ),
        migrations.AddField(
            model_name='estados',
            name='tipo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.tipos_estados'),
        ),
        migrations.CreateModel(
            name='Historial_Stock',
            fields=[
                ('id_historial_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_hstock', models.CharField(max_length=100)),
                ('fecha_movimiento_hstock', models.DateTimeField(auto_now_add=True)),
                ('stock_anterior_hstock', models.IntegerField()),
                ('stock_nuevo_hstock', models.IntegerField()),
                ('observaciones_hstock', models.CharField(max_length=300)),
                ('DELETE_Hstock', models.BooleanField(default=False)),
                ('empleado_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('stock_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.stocks')),
                ('tipo_movimiento_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.tipos_movimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones_Puntos',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('DELETE_Trans', models.BooleanField(default=True)),
                ('cliente_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Puntajes',
            fields=[
                ('id_puntaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntos_acumulados', models.BigIntegerField()),
                ('puntos_utilizados', models.BigIntegerField()),
                ('DELETE_Puntaje', models.BooleanField(default=False)),
                ('transaccion_puntaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.transacciones_puntos')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('observaciones_venta', models.CharField(max_length=200)),
                ('DELETE_Vent', models.BooleanField(default=False)),
                ('caja_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cajas')),
                ('cliente_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
                ('empleado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('estado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.AddField(
            model_name='transacciones_puntos',
            name='origen_puntos_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ventas'),
        ),
        migrations.CreateModel(
            name='Detalle_Ventas',
            fields=[
                ('id_det_vent', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario_det_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_det_vent', models.IntegerField()),
                ('subtotal_det_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_det_vent', models.CharField(max_length=200)),
                ('DELETE_Det_Vent', models.BooleanField(default=False)),
                ('cupon_canje_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cupones_clientes')),
                ('producto_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
                ('venta_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='HOME.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELETE_Vent_MetPag', models.BooleanField(default=False)),
                ('metodopago_vent_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.metodos_pago')),
                ('venta_vent_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ventas')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metodopago_vent_metpag', 'venta_vent_metpag'), name='unique_venta_metodopago_combinacion')],
            },
        ),
    ]
