# Generated by Django 5.2.1 on 2025-09-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_productos_barcode_productos_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='es_credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compras',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Compra_MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='HOME.compras')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.metodos_pago')),
            ],
            options={
                'unique_together': {('compra', 'metodo_pago')},
            },
        ),
    ]
