# Generated by Django 5.2.1 on 2025-09-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_compras_es_credito_compras_fecha_limite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_ventas',
            name='cupon_canje_det_vent',
        ),
        migrations.AddField(
            model_name='ventas',
            name='cupon_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.cupones_clientes'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventas',
            name='vuelto_entregado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
