# Generated by Django 5.2.1 on 2025-09-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_remove_detalle_ventas_cupon_canje_det_vent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones_puntos',
            name='cliente_transaccion',
        ),
        migrations.RemoveField(
            model_name='transacciones_puntos',
            name='origen_puntos_transaccion',
        ),
        migrations.CreateModel(
            name='Historial_Puntos',
            fields=[
                ('id_historial_puntos', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_movidos', models.IntegerField()),
                ('puntos_anteriores', models.IntegerField()),
                ('puntos_nuevos', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('GANADOS', 'Ganados por compra'), ('CANJEADOS', 'Canjeados por cupón'), ('AJUSTE', 'Ajuste manual')], max_length=20)),
                ('DELETE_Hist_Puntos', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='HOME.clientes')),
                ('cupon_canjeado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.cupones_clientes')),
                ('venta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.ventas')),
            ],
        ),
        migrations.DeleteModel(
            name='Puntajes',
        ),
        migrations.DeleteModel(
            name='Transacciones_Puntos',
        ),
    ]
