# Generated by Django 5.2.1 on 2025-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0005_remove_transacciones_puntos_cliente_transaccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFidelizacion',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracion de Fidelizacion',
                'verbose_name_plural': 'Configuraciones de Fidelizacion',
            },
        ),
    ]
