# Generated by Django 5.2.1 on 2025-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_configuracionfidelizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='puntos_cargados_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventas',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
