# Generated by Django 5.2.1 on 2025-09-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_ventas_puntos_cargados_qr_ventas_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_movimientos',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
