# Generated by Django 5.2.1 on 2025-09-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_tipos_movimientos_is_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Movimientos_Financieros',
            fields=[
                ('id_historial_mov_fin', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_mov_fin', models.DateTimeField(auto_now_add=True)),
                ('monto_mov_fin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Hist_Mov_Fin', models.BooleanField(default=False)),
                ('Historial_Caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME.historial_caja')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones_Puntos',
            fields=[
                ('id_trans_puntos', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_trans_puntos', models.DateTimeField(auto_now_add=True)),
                ('puntos_transaccion', models.IntegerField()),
                ('descripcion_trans_puntos', models.CharField(max_length=200)),
                ('DELETE_Trans_Puntos', models.BooleanField(default=False)),
                ('cliente_trans_puntos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cupones_Descuento',
            new_name='Promociones_Descuento',
        ),
        migrations.RenameModel(
            old_name='Cupones_Clientes',
            new_name='Promos_Clientes',
        ),
        migrations.DeleteModel(
            name='ConfiguracionFidelizacion',
        ),
        migrations.RenameField(
            model_name='compra_metodopago',
            old_name='compra',
            new_name='compra_comp_metpag',
        ),
        migrations.RenameField(
            model_name='compra_metodopago',
            old_name='metodo_pago',
            new_name='metodo_pago_comp_metpag',
        ),
        migrations.RenameField(
            model_name='compra_metodopago',
            old_name='monto',
            new_name='monto_comp_metpag',
        ),
        migrations.RenameField(
            model_name='historial_puntos',
            old_name='fecha_movimiento',
            new_name='fecha_mov_hist_puntos',
        ),
        migrations.RenameField(
            model_name='historial_puntos',
            old_name='cupon_canjeado',
            new_name='promo_usada_hist_puntos',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='DELETE_Cupon_Desc',
            new_name='DELETE_Promo_Desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='descripcion_cupon_desc',
            new_name='descripcion_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='descuento_monto_cupon_desc',
            new_name='descuento_monto_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='descuento_porcentaje_cupon_desc',
            new_name='descuento_porcentaje_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='fecha_inicio_cupon_desc',
            new_name='fecha_inicio_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='fecha_vencimiento_cupon_desc',
            new_name='fecha_vencimiento_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='id_cupon_desc',
            new_name='id_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='nombre_cupon_desc',
            new_name='nombre_promo_desc',
        ),
        migrations.RenameField(
            model_name='promociones_descuento',
            old_name='puntos_requeridos_cupon_desc',
            new_name='puntos_requeridos_promo_desc',
        ),
        migrations.RenameField(
            model_name='promos_clientes',
            old_name='DELETE_Cupon_Clie',
            new_name='DELETE_promo_Clie',
        ),
        migrations.RenameField(
            model_name='promos_clientes',
            old_name='cliente_cupon_cli',
            new_name='cliente_promo_cli',
        ),
        migrations.RenameField(
            model_name='promos_clientes',
            old_name='cupon_descuento_cupon_cli',
            new_name='cupon_descuento_promo_cli',
        ),
        migrations.RenameField(
            model_name='promos_clientes',
            old_name='estado_cupon_cli',
            new_name='estado_promo_cli',
        ),
        migrations.RenameField(
            model_name='promos_clientes',
            old_name='id_cupon_cli',
            new_name='id_promo_cli',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='cupon_aplicado',
            new_name='promo_aplicada',
        ),
        migrations.AlterUniqueTogether(
            name='compra_metodopago',
            unique_together={('compra_comp_metpag', 'metodo_pago_comp_metpag')},
        ),
        migrations.RemoveField(
            model_name='compras',
            name='es_credito',
        ),
        migrations.RemoveField(
            model_name='fondo_pagos',
            name='nombre_fp',
        ),
        migrations.RemoveField(
            model_name='historial_puntos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historial_puntos',
            name='tipo_movimiento',
        ),
        migrations.RemoveField(
            model_name='historial_puntos',
            name='venta_origen',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='marca_producto',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='descuento_aplicado',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='puntos_cargados_qr',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='qr_token',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='vuelto_entregado',
        ),
        migrations.AddField(
            model_name='compra_metodopago',
            name='DELETE_Comp_MetPag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra_metodopago',
            name='id_comp_metpag',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='historial_puntos',
            name='tipo_mov_hist_puntos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME.tipos_movimientos'),
        ),
        migrations.AddField(
            model_name='movimiento_fondo',
            name='DELETE_Mov_Fp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_vencimiento_producto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento_fondo',
            name='tipo_mov_fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.tipos_movimientos'),
        ),
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='Movimiento_Fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME.movimiento_fondo'),
        ),
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='caja_mov_fin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cajas'),
        ),
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='compra_mov_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME.compras'),
        ),
        migrations.AddField(
            model_name='historial_movimientos_financieros',
            name='venta_mov_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME.ventas'),
        ),
        migrations.AddField(
            model_name='historial_puntos',
            name='trans_hist_puntos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='HOME.transacciones_puntos'),
        ),
        migrations.RemoveField(
            model_name='compra_metodopago',
            name='id',
        ),
    ]
