# Generated by Django 5.2.1 on 2025-09-15 20:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_historial_movimientos_financieros_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compra_metodopago',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ventas',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ventas',
            name='vuelto_entregado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='historial_caja',
            name='cantidad_movida_hcaja',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
