# Generated by Django 5.2.1 on 2025-09-26 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0010_alter_compra_metodopago_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha_vencimiento_producto',
        ),
    ]
