# Generated by Django 5.2.1 on 2025-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0011_remove_productos_fecha_vencimiento_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_vencimiento_producto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
