# Generated by Django 5.2.1 on 2025-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0013_alter_productos_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='qr_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
