# Generated by Django 5.2.1 on 2025-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0014_ventas_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
