# Generated by Django 5.2.1 on 2025-10-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0015_ventas_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_stock',
            name='cantidad_hstock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedores_productos',
            name='precio_unitario_prov_x_prod',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='producto_en_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='HOME.productos'),
        ),
    ]
