# Generated by Django 5.2.1 on 2025-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0016_alter_historial_stock_cantidad_hstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_stock',
            name='cantidad_hstock',
            field=models.CharField(max_length=255),
        ),
    ]
