# Generated by Django 5.2.1 on 2025-10-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0017_alter_historial_stock_cantidad_hstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_caja',
            name='destino_movimiento',
        ),
    ]
