# Generated by Django 5.2.1 on 2025-10-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0018_remove_historial_caja_destino_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_caja',
            name='destino_movimiento',
            field=models.CharField(blank=True, choices=[('DEPOSITAR_OTROS', 'Depositar/Otros'), ('PARA_PAGOS_FONDO', 'Para pagos (Fondo)'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
    ]
