# Generated by Django 5.2.1 on 2025-10-21 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abrir_Cerrar_CAJA', '0001_initial'),
        ('Control_STOCK', '0001_initial'),
        ('Fidelizar_CLIENTES', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('RETIRO_CAJA', 'Retiro de Caja'), ('VENTA_NUEVA', 'Venta Nueva'), ('COMPRA_NUEVA', 'Compra Nueva'), ('ANULACION_VENTA', 'Anulación de Venta'), ('AJUSTE_STOCK_MANUAL', 'Ajuste Manual de Stock'), ('COMPRA_RECIBIDA', 'Compra Marcada como Recibida'), ('AJUSTE_PUNTOS_MANUAL', 'Ajuste Manual de Puntos'), ('LOGIN_FALLIDO', 'Intento de Login Fallido'), ('MODELO_CREADO', 'Modelo Creado'), ('MODELO_ACTUALIZADO', 'Modelo Actualizado'), ('MODELO_ELIMINADO', 'Modelo Eliminado')], help_text='Tipo de acción realizada.', max_length=50)),
                ('detalles', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON sobre el evento.', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el evento.')),
                ('historial_caja', models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de caja.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Abrir_Cerrar_CAJA.historial_caja')),
                ('historial_movimientos_financieros', models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de movimientos financieros.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Abrir_Cerrar_CAJA.historial_movimientos_financieros')),
                ('historial_puntos', models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de puntos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fidelizar_CLIENTES.historial_puntos')),
                ('historial_stock', models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Control_STOCK.historial_stock')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
