# Generated by Django 5.2.1 on 2025-09-03 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('RETIRO_CAJA', 'Retiro de Caja'), ('VENTA_NUEVA', 'Venta Nueva'), ('COMPRA_NUEVA', 'Compra Nueva')], help_text='Tipo de acción realizada.', max_length=50)),
                ('detalles', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON sobre el evento.', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el evento.')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
