# Generated by Django 5.2.1 on 2025-09-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0002_alter_registroauditoria_accion'),
        ('HOME', '0009_historial_movimientos_financieros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='historial_caja',
            field=models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de caja.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.historial_caja'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='historial_movimientos_financieros',
            field=models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de movimientos financieros.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.historial_movimientos_financieros'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='historial_puntos',
            field=models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de puntos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.historial_puntos'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='historial_stock',
            field=models.ForeignKey(blank=True, help_text='Enlace a un registro de historial de stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.historial_stock'),
        ),
    ]
