# Generated by Django 5.2.1 on 2025-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0003_registroauditoria_historial_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('RETIRO_CAJA', 'Retiro de Caja'), ('VENTA_NUEVA', 'Venta Nueva'), ('COMPRA_NUEVA', 'Compra Nueva'), ('ANULACION_VENTA', 'Anulación de Venta'), ('AJUSTE_STOCK_MANUAL', 'Ajuste Manual de Stock'), ('COMPRA_RECIBIDA', 'Compra Marcada como Recibida'), ('AJUSTE_PUNTOS_MANUAL', 'Ajuste Manual de Puntos'), ('LOGIN_FALLIDO', 'Intento de Login Fallido'), ('MODELO_CREADO', 'Modelo Creado'), ('MODELO_ACTUALIZADO', 'Modelo Actualizado'), ('MODELO_ELIMINADO', 'Modelo Eliminado')], help_text='Tipo de acción realizada.', max_length=50),
        ),
    ]
