# Generated by Django 5.2.1 on 2025-09-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.BigIntegerField()),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('total_ventas_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_ventas_empleado', models.IntegerField(default=0)),
                ('fecha_reporte', models.DateField()),
            ],
            options={
                'unique_together': {('empleado_id', 'fecha_reporte')},
            },
        ),
        migrations.CreateModel(
            name='ReporteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_reporte', models.DateField()),
            ],
            options={
                'unique_together': {('producto_id', 'fecha_reporte')},
            },
        ),
    ]
