# Generated by Django 5.2.1 on 2025-10-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Config_PR', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones_Descuento',
            fields=[
                ('id_promo_desc', models.BigAutoField(primary_key=True, serialize=False)),
                ('descuento_porcentaje_promo_desc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_monto_promo_desc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_requeridos_promo_desc', models.IntegerField()),
                ('nombre_promo_desc', models.CharField(max_length=100)),
                ('descripcion_promo_desc', models.CharField(max_length=300)),
                ('fecha_inicio_promo_desc', models.DateField()),
                ('fecha_vencimiento_promo_desc', models.DateField()),
                ('DELETE_Promo_Desc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Puntos',
            fields=[
                ('id_historial_puntos', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_obtenidos_historial_puntos', models.IntegerField()),
                ('puntos_redimidos_historial_puntos', models.IntegerField()),
                ('fecha_historial_puntos', models.DateField(auto_now_add=True)),
                ('descripcion_historial_puntos', models.CharField(max_length=300)),
                ('DELETE_HP', models.BooleanField(default=False)),
                ('cliente_historial_puntos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Promos_Clientes',
            fields=[
                ('id_promo_cli', models.BigAutoField(primary_key=True, serialize=False)),
                ('DELETE_promo_Clie', models.BooleanField(default=False)),
                ('cliente_promo_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.clientes')),
                ('cupon_descuento_promo_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fidelizar_CLIENTES.promociones_descuento')),
                ('estado_promo_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config_PR.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones_Puntos',
            fields=[
                ('id_trans_puntos', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntos_trans_puntos', models.IntegerField()),
                ('fecha_trans_puntos', models.DateField(auto_now_add=True)),
                ('descripcion_trans_puntos', models.CharField(max_length=300)),
                ('DELETE_Trans_Puntos', models.BooleanField(default=False)),
                ('cliente_trans_puntos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.clientes')),
            ],
        ),
    ]
