# Generated by Django 5.2.1 on 2025-10-27 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fidelizar_CLIENTES', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones_puntos',
            name='cliente_trans_puntos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_transacciones', to='autenticacion.clientes'),
        ),
    ]
